FROM node:20

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY tsconfig.json ./
COPY src ./src

RUN npx playwright install --with-deps

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]